version: "3.9"

services:
  library-app-comments:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: damou/library-app-comments:dev
    container_name: library-app-comments-container
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/src
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://library-app-comments-db:27017/comments
    command: npm run dev
    depends_on:
      - library-app-comments-db
    networks:
      - library-app-network

  library-app-comments-db:
    image: mongo:latest
    container_name: library-app-comments-db
    hostname: mongodb
    ports:
      - "27018:27017"
    networks:
      - library-app-network

networks:
  library-app-network:
    external: true